DROP TABLE IF EXISTS WO_BOOK;
CREATE TABLE WO_BOOK (
  ISBN VARCHAR(30) PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  AUTHOR VARCHAR(50) NOT NULL,
  PRICE DOUBLE NOT NULL
);

INSERT INTO WO_BOOK(ISBN, NAME, AUTHOR, PRICE) VALUES('isbn', 'book name', 'author', 55.20);