DROP TABLE IF EXISTS WO_TAG;
CREATE TABLE WO_TAG (
  ID INT PRIMARY KEY NOT NULL auto_increment,
  TAG VARCHAR(30) NOT NULL UNIQUE,
  COLOR VARCHAR(10)
);

INSERT INTO WO_TAG(TAG, COLOR) VALUES('IT', 'PURPLE'), ('Science', 'BLUE');