DROP TABLE IF EXISTS `WO_BOOK`;
CREATE TABLE WO_BOOK (
  ISBN CHAR(13) PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL,
  AUTHOR VARCHAR(50) NOT NULL,
  PRICE DECIMAL(6, 2) NOT NULL
)
INSERT INTO WO_BOOK(ISBN, `NAME`, AUTHOR, PRICE) VALUES('1234567890123', 'TEST BOOK NAME', 'test', 55.2);